<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Layout
    |--------------------------------------------------------------------------
    |
    | In the following options you can configure the application links.
    |
    */

    'navbar' => [
        'search' => [
            'show' => true,
            'route' => null,
        ],
        'items' => [
            [
                'code'              => 'notifications',
                'icon'              => 'heroicon-s-bell',
                'text'              => 'View notifications',
                'tooltip'           => null,
                'route_name'        => null,
                'is_theme_toggle'   => false,
                'is_user'           => false,
                'dropdown'          => [
                    'is_list'           => true,
                    'is_square'         => false,
                    'get_data_action'   => 'getNavbarNotifications',
                    'header'            => 'Notifications',
                    'footer'            => [
                        'icon'       => 'heroicon-s-eye',
                        'text'       => 'View all',
                        'route_name' => null,
                    ],
                ],
            ],
            [
                'code'              => 'apps',
                'icon'              => 'heroicon-s-squares-2x2',
                'text'              => 'View other links of the application',
                'tooltip'           => null,
                'route_name'        => null,
                'is_theme_toggle'   => false,
                'is_user'           => false,
                'dropdown'          => [
                    'is_list'           => false,
                    'is_square'         => true,
                    'get_data_action'   => null,
                    'header'            => 'Apps',
                    'footer'            => null,
                    'items'             => [
                        [
                            'icon'          => 'heroicon-s-shopping-bag',
                            'text'          => 'Sales',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-user-group',
                            'text'          => 'Users',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-inbox',
                            'text'          => 'Inbox',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-user-circle',
                            'text'          => 'Profile',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-cog-8-tooth',
                            'text'          => 'Settings',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-archive-box',
                            'text'          => 'Products',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-currency-dollar',
                            'text'          => 'Pricing',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-receipt-percent',
                            'text'          => 'Billing',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-arrow-left-end-on-rectangle',
                            'text'          => 'Logout',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                    ]
                ],
            ],
            [
                'is_theme_toggle'   => true,
            ],
            [
                'code'              => 'user',
                'icon'              => null,
                'text'              => 'Open user menu',
                'tooltip'           => null,
                'route_name'        => null,
                'is_theme_toggle'   => false,
                'is_user'           => true,
                'dropdown'          => [
                    'is_list'           => false,
                    'is_square'         => false,
                    'get_data_action'   => 'getUserInfo',
                    'header'            => null,
                    'footer'            => null,
                    'items'             => [
                        [
                            'icon'          => null,
                            'text'          => 'My profile',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => null,
                            'text'          => 'Account settings',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'is_separator'  => true,
                        ],
                        [
                            'icon'          => 'heroicon-s-heart',
                            'text'          => 'My likes',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-rectangle-stack',
                            'text'          => 'Collections',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'icon'          => 'heroicon-s-fire;text-blue-600 dark:text-blue-500',
                            'text'          => 'Pro version',
                            'tooltip'       => null,
                            'route_name'    => null,
                            'is_separator'  => false,
                        ],
                        [
                            'is_separator'  => true,
                        ],
                        [
                            'icon'          => 'heroicon-s-arrow-left-end-on-rectangle',
                            'text'          => 'Log Out',
                            'tooltip'       => null,
                            'route_name'    => 'logout',
                            'is_post'       => true,
                            'is_separator'  => false,
                        ],
                    ],
                ],
            ],
        ],
    ],

    'sidebar' => [
        'search' => [
            'show' => true,
            'route' => null,
        ],
        'items' => [
            [
                'code'              => null,
                'icon'              => 'heroicon-s-chart-pie',
                'text'              => 'Overview',
                'short_text'        => 'Overview',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => null,
            ],
            [
                'code'              => null,
                'icon'              => 'heroicon-s-document-text',
                'text'              => 'Pages',
                'short_text'        => 'Pages',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => [
                    [
                        'code'              => null,
                        'text'              => 'Settings',
                        'short_text'        => 'Settings',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                    [
                        'code'              => null,
                        'text'              => 'Kanban',
                        'short_text'        => 'Kanban',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                    [
                        'code'              => null,
                        'text'              => 'Calendar',
                        'short_text'        => 'Calendar',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                ],
            ],
            [
                'code'              => null,
                'icon'              => 'heroicon-s-shopping-bag',
                'text'              => 'Sales',
                'short_text'        => 'Sales',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => [
                    [
                        'code'              => null,
                        'text'              => 'Products',
                        'short_text'        => 'Products',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                    [
                        'code'              => null,
                        'text'              => 'Billing',
                        'short_text'        => 'Billing',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                    [
                        'code'              => null,
                        'text'              => 'Invoice',
                        'short_text'        => 'Invoice',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                ],
            ],
            [
                'code'              => null,
                'icon'              => 'heroicon-s-inbox-arrow-down',
                'text'              => 'Messages',
                'short_text'        => 'Messages',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => 'getMessageCounter',
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => null,
            ],
            [
                'code'              => null,
                'icon'              => 'heroicon-s-lock-closed',
                'text'              => 'Authentication',
                'short_text'        => 'Auth',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => [
                    [
                        'code'              => null,
                        'text'              => 'Sign In',
                        'short_text'        => 'Sign In',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                    [
                        'code'              => null,
                        'text'              => 'Sign Up',
                        'short_text'        => 'Sign Up',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                    [
                        'code'              => null,
                        'text'              => 'Forgot Password',
                        'short_text'        => 'Forgot Pass',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                    ],
                ],
            ],
            //----- is_separator -----------------------------
            [
                'is_separator' => true,
            ],
            //----- end is_separator -----------------------------
            [
                'code'              => null,
                'icon'              => 'heroicon-s-clipboard-document-list',
                'text'              => 'Docs',
                'short_text'        => 'Docs',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => null,
            ],
            [
                'code'              => null,
                'icon'              => 'heroicon-s-rectangle-stack',
                'text'              => 'Components',
                'short_text'        => 'Components',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => null,
            ],
            [
                'code'              => null,
                'icon'              => 'heroicon-s-lifebuoy',
                'text'              => 'Help',
                'short_text'        => 'Help',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => null,
            ],
            [
                'code'              => null,
                'icon'              => 'heroicon-s-document-text',
                'text'              => 'Kalion',
                'short_text'        => 'Kalion',
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => [
                    [
                        'code'              => 'h-pages',
                        'text'              => 'Pages',
                        'short_text'        => 'Pages',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                        'dropdown'          => [
                            [
                                'code'              => null,
                                'text'              => 'Laravel Welcome',
                                'short_text'        => 'Welcome',
                                'tooltip'           => null,
                                'route_name'        => 'welcome',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Root',
                                'short_text'        => 'Root',
                                'tooltip'           => null,
                                'route_name'        => 'index',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Queued Jobs (Pending)',
                                'short_text'        => 'Queued Jobs',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.queues.queuedJobs',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Failed Jobs (Pending)',
                                'short_text'        => 'Failed Jobs',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.queues.failedJobs',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Compare Html',
                                'short_text'        => 'Compare Html',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.compareHtml',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Update Cookie',
                                'short_text'        => 'Update Cookie',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.modifyCookie',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Icons',
                                'short_text'        => 'Icons',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.icons',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                        ]
                    ],
                    [
                        'code'              => null,
                        'text'              => 'Examples',
                        'short_text'        => 'Examples',
                        'tooltip'           => null,
                        'route_name'        => null,
                        'counter_action'    => null,
                        'collapsed'         => false,
                        'dropdown'          => [
                            [
                                'code'              => null,
                                'text'              => 'Example 1',
                                'short_text'        => 'Example 1',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.example1',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Example 2',
                                'short_text'        => 'Example 2',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.example2',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Example 3',
                                'short_text'        => 'Example 3',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.example3',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                            [
                                'code'              => null,
                                'text'              => 'Example 4',
                                'short_text'        => 'Example 4',
                                'tooltip'           => null,
                                'route_name'        => 'kalion.example4',
                                'counter_action'    => null,
                                'collapsed'         => false,
                            ],
                        ]
                    ],
                ],
            ],
        ],
        'footer' => [
            [
                'code'              => null,
                'icon'              => 'heroicon-s-adjustments-vertical',
                'text'              => null,
                'short_text'        => null,
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => null,
            ],
            [
                'code'              => 'settings',
                'icon'              => 'heroicon-s-cog-8-tooth',
                'text'              => null,
                'short_text'        => null,
                'tooltip'           => 'Settings page',
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => null,
            ],
            [
                'code'              => 'language',
                'icon'              => 'kal::icon.flag.us-1',
                'text'              => null,
                'short_text'        => null,
                'tooltip'           => null,
                'route_name'        => null,
                'counter_action'    => null,
                'collapsed'         => false,
                'is_separator'      => false,
                'dropdown'          => [
                    [
                        'icon'              => 'kal::icon.flag.us-2',
                        'text'              => 'English (US)',
                        'route_name'        => null,
                        'collapsed'         => false,
                    ],
                    [
                        'icon'              => 'kal::icon.flag.de',
                        'text'              => 'Deutsch',
                        'route_name'        => null,
                        'collapsed'         => false,
                    ],
                    [
                        'icon'              => 'kal::icon.flag.it',
                        'text'              => 'Italiano',
                        'route_name'        => null,
                        'collapsed'         => false,
                    ],
                    [
                        'icon'              => 'kal::icon.flag.cn',
                        'text'              => '中文 (繁體)',
                        'route_name'        => null,
                        'collapsed'         => false,
                    ],
                ],
            ],
        ]
    ],
];
